dist: xenial
install:
 - pip install -U --force-reinstall -r requirements-travis.txt
language: python
python:
 - 3.4
 - 3.5
 - 3.6
 - 3.7
script:
 - python --version
 - pip list
 - pytest --cov=src
 - do_rest=$( echo $TRAVIS_PYTHON_VERSION | grep -e '^3\.6' | wc -l )
 - if [ $do_rest -gt 0 ]; then codecov; else echo "No codecov."; fi
 - if [ $do_rest -gt 0 ]; then pip install black; black --check .; else echo "No black."; fi
