parameters:
  pythons: []
#  images: []

jobs:
- ${{ each python in parameters.pythons }}:
  - job: ${{ coalesce(python.value.name, python.key) }}
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.value.spec)'
          architecture: 'x64'
        displayName: Use cached Python $(python.value.spec) for tests.

      - script: pip install -r requirements-ci.txt
        displayName: Install CI requirements

      - script: pytest -v
        displayName: Run pytest (Python $(python.value.spec))
