trigger:
  - master

pr:
  branches:
    include:
    - master


jobs:
- template: azure-job.yml
  parameters:
    pythons:
      py34:
        spec: '3.4'
      py35:
        spec: '3.5'
      py36:
        spec: '3.6'
      py37:
        spec: '3.7'
    images: [linux, windows, macOs]

